/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  aboutImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  aboutBiuTitle?: string;
  biuFoundedYear?: string;
  biuDescription?: string;
  email?: string;
  telephone1?: string;
  telephone2?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  location?: string;
  size?: string;
  year?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  sketchImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageGallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  finalizado?: boolean;
  mapImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/lib/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project"] | order(_createdAt desc) {    _id,    _type,    _createdAt,    _updatedAt,    title,    location,    size,    year,    description,    finalizado,    mainImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  hotspot,  crop    },    sketchImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  hotspot,  crop    },    mapImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  hotspot,  crop    },    imageGallery[] {        _key,    asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  hotspot,  crop    }  }
export type ProjectsQueryResult = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  location: string | null;
  size: string | null;
  year: string | null;
  description: string | null;
  finalizado: boolean | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  sketchImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  mapImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  imageGallery: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: projectByIdQuery
// Query: *[_type == "project" && _id == $id][0] {    _id,    _type,    _createdAt,    _updatedAt,    title,    location,    size,    year,    description,    finalizado,    mainImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  hotspot,  crop    },    sketchImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  hotspot,  crop    },    mapImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  hotspot,  crop    },    imageGallery[] {        _key,    asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  hotspot,  crop    }  }
export type ProjectByIdQueryResult = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  location: string | null;
  size: string | null;
  year: string | null;
  description: string | null;
  finalizado: boolean | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  sketchImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  mapImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  imageGallery: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0] {    _id,    _type,    _createdAt,    _updatedAt,    aboutBiuTitle,    biuFoundedYear,    biuDescription,    email,    telephone1,    telephone2,    aboutImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  hotspot,  crop    }  }
export type AboutPageQueryResult = {
  _id: "aboutPage";
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  aboutBiuTitle: string | null;
  biuFoundedYear: string | null;
  biuDescription: string | null;
  email: string | null;
  telephone1: string | null;
  telephone2: string | null;
  aboutImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project"] | order(_createdAt desc) {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    title,\n    location,\n    size,\n    year,\n    description,\n    finalizado,\n    mainImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    },\n    sketchImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    },\n    mapImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    },\n    imageGallery[] {\n      \n  _key,\n  \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n\n    }\n  }\n': ProjectsQueryResult;
    '\n  *[_type == "project" && _id == $id][0] {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    title,\n    location,\n    size,\n    year,\n    description,\n    finalizado,\n    mainImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    },\n    sketchImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    },\n    mapImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    },\n    imageGallery[] {\n      \n  _key,\n  \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n\n    }\n  }\n': ProjectByIdQueryResult;
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0] {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    aboutBiuTitle,\n    biuFoundedYear,\n    biuDescription,\n    email,\n    telephone1,\n    telephone2,\n    aboutImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    }\n  }\n': AboutPageQueryResult;
  }
}
