/**
 * App-facing schema types. Document and query result types are generated by
 * Sanity TypeGen (`npm run typegen` → `sanity.types.ts`).
 */
import type {
  AboutPage as AboutPageDocument,
  AboutPageQueryResult,
  Project as ProjectDocument,
  ProjectByIdQueryResult,
  ProjectsQueryResult,
} from '../sanity.types'

/** `true` = finalizado, `false` or unset = en desarrollo */
export type ProjectFinalizado = boolean

export type {
  AboutPageDocument,
  AboutPageQueryResult,
  ProjectDocument,
  ProjectByIdQueryResult,
  ProjectsQueryResult,
}

/** Single project returned by `projectsQuery` */
export type Project = NonNullable<ProjectsQueryResult>[number]

/** About page singleton returned by `aboutPageQuery` */
export type AboutPage = NonNullable<AboutPageQueryResult>
